#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea_9_10
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Datos_Feligrense")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertPaises(Paises instance);
    partial void UpdatePaises(Paises instance);
    partial void DeletePaises(Paises instance);
    partial void InsertDATOS(DATOS instance);
    partial void UpdateDATOS(DATOS instance);
    partial void DeleteDATOS(DATOS instance);
    partial void InsertAspNetUsers(AspNetUsers instance);
    partial void UpdateAspNetUsers(AspNetUsers instance);
    partial void DeleteAspNetUsers(AspNetUsers instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["FeligrenseDbContext"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Paises> Paises
		{
			get
			{
				return this.GetTable<Paises>();
			}
		}
		
		public System.Data.Linq.Table<DATOS> DATOS
		{
			get
			{
				return this.GetTable<DATOS>();
			}
		}
		
		public System.Data.Linq.Table<AspNetUsers> AspNetUsers
		{
			get
			{
				return this.GetTable<AspNetUsers>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Paises")]
	public partial class Paises : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nombre;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public Paises()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(70)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DATOS")]
	public partial class DATOS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Sexo;
		
		private string _Fecha;
		
		private string _Pais;
		
		private string _Ciudad;
		
		private string _Pais_Residencia_Actual;
		
		private string _Ciudad_Residencia_Actual;
		
		private string _Direccion;
		
		private string _Telefono;
		
		private string _Celular;
		
		private string _Correo_electronico;
		
		private string _Tipo_documento;
		
		private string _Documento_identidad;
		
		private string _Estado_Civil;
		
		private string _Nombre_Pareja;
		
		private string _Hijos;
		
		private System.Nullable<int> _N_Hijos;
		
		private string _Profesion;
		
		private string _Ocupacion_Actual;
		
		private string _Nombre_Empresa;
		
		private string _Telefono_Empresa;
		
		private string _Fecha_Conversion;
		
		private string _Fecha_Bautismo;
		
		private string _Fecha_Aceptado;
		
		private string _Denominacion_Pertenece;
		
		private string _Otra_denominacion;
		
		private string _Nombre_Iglesia;
		
		private string _Congregacion_Anterior;
		
		private string _Nombre_Pastor;
		
		private string _Diciplinado_algunaVez;
		
		private System.Nullable<int> _N_veces;
		
		private string _Causas;
		
		private string _Ocupacion_en_la_iglesia;
		
		private string _Ministerio_Servido;
		
		private string _Ministerio_Fruto;
		
		private string _Ministerio_Dios;
		
		private string _Meta_vida;
		
		private string _Eclesiastico_estudio;
		
		private string _Nivel_estudio;
		
		private string _Expulsado_Ins;
		
		private string _Razon;
		
		private System.Nullable<int> _DBHABILITADO;
		
		private System.Data.Linq.Binary _Foto;
		
		private string _Usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnSexoChanging(string value);
    partial void OnSexoChanged();
    partial void OnFechaChanging(string value);
    partial void OnFechaChanged();
    partial void OnPaisChanging(string value);
    partial void OnPaisChanged();
    partial void OnCiudadChanging(string value);
    partial void OnCiudadChanged();
    partial void OnPais_Residencia_ActualChanging(string value);
    partial void OnPais_Residencia_ActualChanged();
    partial void OnCiudad_Residencia_ActualChanging(string value);
    partial void OnCiudad_Residencia_ActualChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnCelularChanging(string value);
    partial void OnCelularChanged();
    partial void OnCorreo_electronicoChanging(string value);
    partial void OnCorreo_electronicoChanged();
    partial void OnTipo_documentoChanging(string value);
    partial void OnTipo_documentoChanged();
    partial void OnDocumento_identidadChanging(string value);
    partial void OnDocumento_identidadChanged();
    partial void OnEstado_CivilChanging(string value);
    partial void OnEstado_CivilChanged();
    partial void OnNombre_ParejaChanging(string value);
    partial void OnNombre_ParejaChanged();
    partial void OnHijosChanging(string value);
    partial void OnHijosChanged();
    partial void OnN_HijosChanging(System.Nullable<int> value);
    partial void OnN_HijosChanged();
    partial void OnProfesionChanging(string value);
    partial void OnProfesionChanged();
    partial void OnOcupacion_ActualChanging(string value);
    partial void OnOcupacion_ActualChanged();
    partial void OnNombre_EmpresaChanging(string value);
    partial void OnNombre_EmpresaChanged();
    partial void OnTelefono_EmpresaChanging(string value);
    partial void OnTelefono_EmpresaChanged();
    partial void OnFecha_ConversionChanging(string value);
    partial void OnFecha_ConversionChanged();
    partial void OnFecha_BautismoChanging(string value);
    partial void OnFecha_BautismoChanged();
    partial void OnFecha_AceptadoChanging(string value);
    partial void OnFecha_AceptadoChanged();
    partial void OnDenominacion_PerteneceChanging(string value);
    partial void OnDenominacion_PerteneceChanged();
    partial void OnOtra_denominacionChanging(string value);
    partial void OnOtra_denominacionChanged();
    partial void OnNombre_IglesiaChanging(string value);
    partial void OnNombre_IglesiaChanged();
    partial void OnCongregacion_AnteriorChanging(string value);
    partial void OnCongregacion_AnteriorChanged();
    partial void OnNombre_PastorChanging(string value);
    partial void OnNombre_PastorChanged();
    partial void OnDiciplinado_algunaVezChanging(string value);
    partial void OnDiciplinado_algunaVezChanged();
    partial void OnN_vecesChanging(System.Nullable<int> value);
    partial void OnN_vecesChanged();
    partial void OnCausasChanging(string value);
    partial void OnCausasChanged();
    partial void OnOcupacion_en_la_iglesiaChanging(string value);
    partial void OnOcupacion_en_la_iglesiaChanged();
    partial void OnMinisterio_ServidoChanging(string value);
    partial void OnMinisterio_ServidoChanged();
    partial void OnMinisterio_FrutoChanging(string value);
    partial void OnMinisterio_FrutoChanged();
    partial void OnMinisterio_DiosChanging(string value);
    partial void OnMinisterio_DiosChanged();
    partial void OnMeta_vidaChanging(string value);
    partial void OnMeta_vidaChanged();
    partial void OnEclesiastico_estudioChanging(string value);
    partial void OnEclesiastico_estudioChanged();
    partial void OnNivel_estudioChanging(string value);
    partial void OnNivel_estudioChanged();
    partial void OnExpulsado_InsChanging(string value);
    partial void OnExpulsado_InsChanged();
    partial void OnRazonChanging(string value);
    partial void OnRazonChanged();
    partial void OnDBHABILITADOChanging(System.Nullable<int> value);
    partial void OnDBHABILITADOChanged();
    partial void OnFotoChanging(System.Data.Linq.Binary value);
    partial void OnFotoChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    #endregion
		
		public DATOS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(70)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(70)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexo", DbType="VarChar(10)")]
		public string Sexo
		{
			get
			{
				return this._Sexo;
			}
			set
			{
				if ((this._Sexo != value))
				{
					this.OnSexoChanging(value);
					this.SendPropertyChanging();
					this._Sexo = value;
					this.SendPropertyChanged("Sexo");
					this.OnSexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="VarChar(150)")]
		public string Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pais", DbType="VarChar(60)")]
		public string Pais
		{
			get
			{
				return this._Pais;
			}
			set
			{
				if ((this._Pais != value))
				{
					this.OnPaisChanging(value);
					this.SendPropertyChanging();
					this._Pais = value;
					this.SendPropertyChanged("Pais");
					this.OnPaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ciudad", DbType="VarChar(60)")]
		public string Ciudad
		{
			get
			{
				return this._Ciudad;
			}
			set
			{
				if ((this._Ciudad != value))
				{
					this.OnCiudadChanging(value);
					this.SendPropertyChanging();
					this._Ciudad = value;
					this.SendPropertyChanged("Ciudad");
					this.OnCiudadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pais_Residencia_Actual", DbType="VarChar(60)")]
		public string Pais_Residencia_Actual
		{
			get
			{
				return this._Pais_Residencia_Actual;
			}
			set
			{
				if ((this._Pais_Residencia_Actual != value))
				{
					this.OnPais_Residencia_ActualChanging(value);
					this.SendPropertyChanging();
					this._Pais_Residencia_Actual = value;
					this.SendPropertyChanged("Pais_Residencia_Actual");
					this.OnPais_Residencia_ActualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ciudad_Residencia_Actual", DbType="VarChar(60)")]
		public string Ciudad_Residencia_Actual
		{
			get
			{
				return this._Ciudad_Residencia_Actual;
			}
			set
			{
				if ((this._Ciudad_Residencia_Actual != value))
				{
					this.OnCiudad_Residencia_ActualChanging(value);
					this.SendPropertyChanging();
					this._Ciudad_Residencia_Actual = value;
					this.SendPropertyChanged("Ciudad_Residencia_Actual");
					this.OnCiudad_Residencia_ActualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(200)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(15)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Celular", DbType="VarChar(20)")]
		public string Celular
		{
			get
			{
				return this._Celular;
			}
			set
			{
				if ((this._Celular != value))
				{
					this.OnCelularChanging(value);
					this.SendPropertyChanging();
					this._Celular = value;
					this.SendPropertyChanged("Celular");
					this.OnCelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo_electronico", DbType="VarChar(60)")]
		public string Correo_electronico
		{
			get
			{
				return this._Correo_electronico;
			}
			set
			{
				if ((this._Correo_electronico != value))
				{
					this.OnCorreo_electronicoChanging(value);
					this.SendPropertyChanging();
					this._Correo_electronico = value;
					this.SendPropertyChanged("Correo_electronico");
					this.OnCorreo_electronicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo_documento", DbType="VarChar(30)")]
		public string Tipo_documento
		{
			get
			{
				return this._Tipo_documento;
			}
			set
			{
				if ((this._Tipo_documento != value))
				{
					this.OnTipo_documentoChanging(value);
					this.SendPropertyChanging();
					this._Tipo_documento = value;
					this.SendPropertyChanged("Tipo_documento");
					this.OnTipo_documentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Documento_identidad", DbType="VarChar(30)")]
		public string Documento_identidad
		{
			get
			{
				return this._Documento_identidad;
			}
			set
			{
				if ((this._Documento_identidad != value))
				{
					this.OnDocumento_identidadChanging(value);
					this.SendPropertyChanging();
					this._Documento_identidad = value;
					this.SendPropertyChanged("Documento_identidad");
					this.OnDocumento_identidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado_Civil", DbType="VarChar(50)")]
		public string Estado_Civil
		{
			get
			{
				return this._Estado_Civil;
			}
			set
			{
				if ((this._Estado_Civil != value))
				{
					this.OnEstado_CivilChanging(value);
					this.SendPropertyChanging();
					this._Estado_Civil = value;
					this.SendPropertyChanged("Estado_Civil");
					this.OnEstado_CivilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Pareja", DbType="VarChar(50)")]
		public string Nombre_Pareja
		{
			get
			{
				return this._Nombre_Pareja;
			}
			set
			{
				if ((this._Nombre_Pareja != value))
				{
					this.OnNombre_ParejaChanging(value);
					this.SendPropertyChanging();
					this._Nombre_Pareja = value;
					this.SendPropertyChanged("Nombre_Pareja");
					this.OnNombre_ParejaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hijos", DbType="VarChar(5)")]
		public string Hijos
		{
			get
			{
				return this._Hijos;
			}
			set
			{
				if ((this._Hijos != value))
				{
					this.OnHijosChanging(value);
					this.SendPropertyChanging();
					this._Hijos = value;
					this.SendPropertyChanged("Hijos");
					this.OnHijosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_Hijos", DbType="Int")]
		public System.Nullable<int> N_Hijos
		{
			get
			{
				return this._N_Hijos;
			}
			set
			{
				if ((this._N_Hijos != value))
				{
					this.OnN_HijosChanging(value);
					this.SendPropertyChanging();
					this._N_Hijos = value;
					this.SendPropertyChanged("N_Hijos");
					this.OnN_HijosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Profesion", DbType="VarChar(50)")]
		public string Profesion
		{
			get
			{
				return this._Profesion;
			}
			set
			{
				if ((this._Profesion != value))
				{
					this.OnProfesionChanging(value);
					this.SendPropertyChanging();
					this._Profesion = value;
					this.SendPropertyChanged("Profesion");
					this.OnProfesionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ocupacion_Actual", DbType="VarChar(50)")]
		public string Ocupacion_Actual
		{
			get
			{
				return this._Ocupacion_Actual;
			}
			set
			{
				if ((this._Ocupacion_Actual != value))
				{
					this.OnOcupacion_ActualChanging(value);
					this.SendPropertyChanging();
					this._Ocupacion_Actual = value;
					this.SendPropertyChanged("Ocupacion_Actual");
					this.OnOcupacion_ActualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Empresa", DbType="VarChar(70)")]
		public string Nombre_Empresa
		{
			get
			{
				return this._Nombre_Empresa;
			}
			set
			{
				if ((this._Nombre_Empresa != value))
				{
					this.OnNombre_EmpresaChanging(value);
					this.SendPropertyChanging();
					this._Nombre_Empresa = value;
					this.SendPropertyChanged("Nombre_Empresa");
					this.OnNombre_EmpresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono_Empresa", DbType="VarChar(15)")]
		public string Telefono_Empresa
		{
			get
			{
				return this._Telefono_Empresa;
			}
			set
			{
				if ((this._Telefono_Empresa != value))
				{
					this.OnTelefono_EmpresaChanging(value);
					this.SendPropertyChanging();
					this._Telefono_Empresa = value;
					this.SendPropertyChanged("Telefono_Empresa");
					this.OnTelefono_EmpresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Conversion", DbType="VarChar(150)")]
		public string Fecha_Conversion
		{
			get
			{
				return this._Fecha_Conversion;
			}
			set
			{
				if ((this._Fecha_Conversion != value))
				{
					this.OnFecha_ConversionChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Conversion = value;
					this.SendPropertyChanged("Fecha_Conversion");
					this.OnFecha_ConversionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Bautismo", DbType="VarChar(150)")]
		public string Fecha_Bautismo
		{
			get
			{
				return this._Fecha_Bautismo;
			}
			set
			{
				if ((this._Fecha_Bautismo != value))
				{
					this.OnFecha_BautismoChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Bautismo = value;
					this.SendPropertyChanged("Fecha_Bautismo");
					this.OnFecha_BautismoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Aceptado", DbType="VarChar(150)")]
		public string Fecha_Aceptado
		{
			get
			{
				return this._Fecha_Aceptado;
			}
			set
			{
				if ((this._Fecha_Aceptado != value))
				{
					this.OnFecha_AceptadoChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Aceptado = value;
					this.SendPropertyChanged("Fecha_Aceptado");
					this.OnFecha_AceptadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Denominacion_Pertenece", DbType="VarChar(50)")]
		public string Denominacion_Pertenece
		{
			get
			{
				return this._Denominacion_Pertenece;
			}
			set
			{
				if ((this._Denominacion_Pertenece != value))
				{
					this.OnDenominacion_PerteneceChanging(value);
					this.SendPropertyChanging();
					this._Denominacion_Pertenece = value;
					this.SendPropertyChanged("Denominacion_Pertenece");
					this.OnDenominacion_PerteneceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Otra_denominacion", DbType="VarChar(60)")]
		public string Otra_denominacion
		{
			get
			{
				return this._Otra_denominacion;
			}
			set
			{
				if ((this._Otra_denominacion != value))
				{
					this.OnOtra_denominacionChanging(value);
					this.SendPropertyChanging();
					this._Otra_denominacion = value;
					this.SendPropertyChanged("Otra_denominacion");
					this.OnOtra_denominacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Iglesia", DbType="VarChar(60)")]
		public string Nombre_Iglesia
		{
			get
			{
				return this._Nombre_Iglesia;
			}
			set
			{
				if ((this._Nombre_Iglesia != value))
				{
					this.OnNombre_IglesiaChanging(value);
					this.SendPropertyChanging();
					this._Nombre_Iglesia = value;
					this.SendPropertyChanged("Nombre_Iglesia");
					this.OnNombre_IglesiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Congregacion_Anterior", DbType="VarChar(70)")]
		public string Congregacion_Anterior
		{
			get
			{
				return this._Congregacion_Anterior;
			}
			set
			{
				if ((this._Congregacion_Anterior != value))
				{
					this.OnCongregacion_AnteriorChanging(value);
					this.SendPropertyChanging();
					this._Congregacion_Anterior = value;
					this.SendPropertyChanged("Congregacion_Anterior");
					this.OnCongregacion_AnteriorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Pastor", DbType="VarChar(60)")]
		public string Nombre_Pastor
		{
			get
			{
				return this._Nombre_Pastor;
			}
			set
			{
				if ((this._Nombre_Pastor != value))
				{
					this.OnNombre_PastorChanging(value);
					this.SendPropertyChanging();
					this._Nombre_Pastor = value;
					this.SendPropertyChanged("Nombre_Pastor");
					this.OnNombre_PastorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diciplinado_algunaVez", DbType="VarChar(10)")]
		public string Diciplinado_algunaVez
		{
			get
			{
				return this._Diciplinado_algunaVez;
			}
			set
			{
				if ((this._Diciplinado_algunaVez != value))
				{
					this.OnDiciplinado_algunaVezChanging(value);
					this.SendPropertyChanging();
					this._Diciplinado_algunaVez = value;
					this.SendPropertyChanged("Diciplinado_algunaVez");
					this.OnDiciplinado_algunaVezChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_veces", DbType="Int")]
		public System.Nullable<int> N_veces
		{
			get
			{
				return this._N_veces;
			}
			set
			{
				if ((this._N_veces != value))
				{
					this.OnN_vecesChanging(value);
					this.SendPropertyChanging();
					this._N_veces = value;
					this.SendPropertyChanged("N_veces");
					this.OnN_vecesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Causas", DbType="VarChar(70)")]
		public string Causas
		{
			get
			{
				return this._Causas;
			}
			set
			{
				if ((this._Causas != value))
				{
					this.OnCausasChanging(value);
					this.SendPropertyChanging();
					this._Causas = value;
					this.SendPropertyChanged("Causas");
					this.OnCausasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ocupacion_en_la_iglesia", DbType="VarChar(50)")]
		public string Ocupacion_en_la_iglesia
		{
			get
			{
				return this._Ocupacion_en_la_iglesia;
			}
			set
			{
				if ((this._Ocupacion_en_la_iglesia != value))
				{
					this.OnOcupacion_en_la_iglesiaChanging(value);
					this.SendPropertyChanging();
					this._Ocupacion_en_la_iglesia = value;
					this.SendPropertyChanged("Ocupacion_en_la_iglesia");
					this.OnOcupacion_en_la_iglesiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ministerio_Servido", DbType="VarChar(150)")]
		public string Ministerio_Servido
		{
			get
			{
				return this._Ministerio_Servido;
			}
			set
			{
				if ((this._Ministerio_Servido != value))
				{
					this.OnMinisterio_ServidoChanging(value);
					this.SendPropertyChanging();
					this._Ministerio_Servido = value;
					this.SendPropertyChanged("Ministerio_Servido");
					this.OnMinisterio_ServidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ministerio_Fruto", DbType="VarChar(150)")]
		public string Ministerio_Fruto
		{
			get
			{
				return this._Ministerio_Fruto;
			}
			set
			{
				if ((this._Ministerio_Fruto != value))
				{
					this.OnMinisterio_FrutoChanging(value);
					this.SendPropertyChanging();
					this._Ministerio_Fruto = value;
					this.SendPropertyChanged("Ministerio_Fruto");
					this.OnMinisterio_FrutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ministerio_Dios", DbType="VarChar(150)")]
		public string Ministerio_Dios
		{
			get
			{
				return this._Ministerio_Dios;
			}
			set
			{
				if ((this._Ministerio_Dios != value))
				{
					this.OnMinisterio_DiosChanging(value);
					this.SendPropertyChanging();
					this._Ministerio_Dios = value;
					this.SendPropertyChanged("Ministerio_Dios");
					this.OnMinisterio_DiosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Meta_vida", DbType="VarChar(150)")]
		public string Meta_vida
		{
			get
			{
				return this._Meta_vida;
			}
			set
			{
				if ((this._Meta_vida != value))
				{
					this.OnMeta_vidaChanging(value);
					this.SendPropertyChanging();
					this._Meta_vida = value;
					this.SendPropertyChanged("Meta_vida");
					this.OnMeta_vidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Eclesiastico_estudio", DbType="VarChar(10)")]
		public string Eclesiastico_estudio
		{
			get
			{
				return this._Eclesiastico_estudio;
			}
			set
			{
				if ((this._Eclesiastico_estudio != value))
				{
					this.OnEclesiastico_estudioChanging(value);
					this.SendPropertyChanging();
					this._Eclesiastico_estudio = value;
					this.SendPropertyChanged("Eclesiastico_estudio");
					this.OnEclesiastico_estudioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nivel_estudio", DbType="VarChar(40)")]
		public string Nivel_estudio
		{
			get
			{
				return this._Nivel_estudio;
			}
			set
			{
				if ((this._Nivel_estudio != value))
				{
					this.OnNivel_estudioChanging(value);
					this.SendPropertyChanging();
					this._Nivel_estudio = value;
					this.SendPropertyChanged("Nivel_estudio");
					this.OnNivel_estudioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expulsado_Ins", DbType="VarChar(10)")]
		public string Expulsado_Ins
		{
			get
			{
				return this._Expulsado_Ins;
			}
			set
			{
				if ((this._Expulsado_Ins != value))
				{
					this.OnExpulsado_InsChanging(value);
					this.SendPropertyChanging();
					this._Expulsado_Ins = value;
					this.SendPropertyChanged("Expulsado_Ins");
					this.OnExpulsado_InsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Razon", DbType="VarChar(60)")]
		public string Razon
		{
			get
			{
				return this._Razon;
			}
			set
			{
				if ((this._Razon != value))
				{
					this.OnRazonChanging(value);
					this.SendPropertyChanging();
					this._Razon = value;
					this.SendPropertyChanged("Razon");
					this.OnRazonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DBHABILITADO", DbType="Int")]
		public System.Nullable<int> DBHABILITADO
		{
			get
			{
				return this._DBHABILITADO;
			}
			set
			{
				if ((this._DBHABILITADO != value))
				{
					this.OnDBHABILITADOChanging(value);
					this.SendPropertyChanging();
					this._DBHABILITADO = value;
					this.SendPropertyChanged("DBHABILITADO");
					this.OnDBHABILITADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Foto", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Foto
		{
			get
			{
				return this._Foto;
			}
			set
			{
				if ((this._Foto != value))
				{
					this.OnFotoChanging(value);
					this.SendPropertyChanging();
					this._Foto = value;
					this.SendPropertyChanged("Foto");
					this.OnFotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(60)")]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AspNetUsers")]
	public partial class AspNetUsers : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private string _Email;
		
		private bool _EmailConfirmed;
		
		private string _PasswordHash;
		
		private string _SecurityStamp;
		
		private string _PhoneNumber;
		
		private bool _PhoneNumberConfirmed;
		
		private bool _TwoFactorEnabled;
		
		private System.Nullable<System.DateTime> _LockoutEndDateUtc;
		
		private bool _LockoutEnabled;
		
		private int _AccessFailedCount;
		
		private string _UserName;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnEmailConfirmedChanging(bool value);
    partial void OnEmailConfirmedChanged();
    partial void OnPasswordHashChanging(string value);
    partial void OnPasswordHashChanged();
    partial void OnSecurityStampChanging(string value);
    partial void OnSecurityStampChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    partial void OnPhoneNumberConfirmedChanging(bool value);
    partial void OnPhoneNumberConfirmedChanged();
    partial void OnTwoFactorEnabledChanging(bool value);
    partial void OnTwoFactorEnabledChanged();
    partial void OnLockoutEndDateUtcChanging(System.Nullable<System.DateTime> value);
    partial void OnLockoutEndDateUtcChanged();
    partial void OnLockoutEnabledChanging(bool value);
    partial void OnLockoutEnabledChanged();
    partial void OnAccessFailedCountChanging(int value);
    partial void OnAccessFailedCountChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    #endregion
		
		public AspNetUsers()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NVarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(256)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailConfirmed", DbType="Bit NOT NULL")]
		public bool EmailConfirmed
		{
			get
			{
				return this._EmailConfirmed;
			}
			set
			{
				if ((this._EmailConfirmed != value))
				{
					this.OnEmailConfirmedChanging(value);
					this.SendPropertyChanging();
					this._EmailConfirmed = value;
					this.SendPropertyChanged("EmailConfirmed");
					this.OnEmailConfirmedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordHash", DbType="NVarChar(MAX)")]
		public string PasswordHash
		{
			get
			{
				return this._PasswordHash;
			}
			set
			{
				if ((this._PasswordHash != value))
				{
					this.OnPasswordHashChanging(value);
					this.SendPropertyChanging();
					this._PasswordHash = value;
					this.SendPropertyChanged("PasswordHash");
					this.OnPasswordHashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecurityStamp", DbType="NVarChar(MAX)")]
		public string SecurityStamp
		{
			get
			{
				return this._SecurityStamp;
			}
			set
			{
				if ((this._SecurityStamp != value))
				{
					this.OnSecurityStampChanging(value);
					this.SendPropertyChanging();
					this._SecurityStamp = value;
					this.SendPropertyChanged("SecurityStamp");
					this.OnSecurityStampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="NVarChar(MAX)")]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumberConfirmed", DbType="Bit NOT NULL")]
		public bool PhoneNumberConfirmed
		{
			get
			{
				return this._PhoneNumberConfirmed;
			}
			set
			{
				if ((this._PhoneNumberConfirmed != value))
				{
					this.OnPhoneNumberConfirmedChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumberConfirmed = value;
					this.SendPropertyChanged("PhoneNumberConfirmed");
					this.OnPhoneNumberConfirmedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TwoFactorEnabled", DbType="Bit NOT NULL")]
		public bool TwoFactorEnabled
		{
			get
			{
				return this._TwoFactorEnabled;
			}
			set
			{
				if ((this._TwoFactorEnabled != value))
				{
					this.OnTwoFactorEnabledChanging(value);
					this.SendPropertyChanging();
					this._TwoFactorEnabled = value;
					this.SendPropertyChanged("TwoFactorEnabled");
					this.OnTwoFactorEnabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LockoutEndDateUtc", DbType="DateTime")]
		public System.Nullable<System.DateTime> LockoutEndDateUtc
		{
			get
			{
				return this._LockoutEndDateUtc;
			}
			set
			{
				if ((this._LockoutEndDateUtc != value))
				{
					this.OnLockoutEndDateUtcChanging(value);
					this.SendPropertyChanging();
					this._LockoutEndDateUtc = value;
					this.SendPropertyChanged("LockoutEndDateUtc");
					this.OnLockoutEndDateUtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LockoutEnabled", DbType="Bit NOT NULL")]
		public bool LockoutEnabled
		{
			get
			{
				return this._LockoutEnabled;
			}
			set
			{
				if ((this._LockoutEnabled != value))
				{
					this.OnLockoutEnabledChanging(value);
					this.SendPropertyChanging();
					this._LockoutEnabled = value;
					this.SendPropertyChanged("LockoutEnabled");
					this.OnLockoutEnabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccessFailedCount", DbType="Int NOT NULL")]
		public int AccessFailedCount
		{
			get
			{
				return this._AccessFailedCount;
			}
			set
			{
				if ((this._AccessFailedCount != value))
				{
					this.OnAccessFailedCountChanging(value);
					this.SendPropertyChanging();
					this._AccessFailedCount = value;
					this.SendPropertyChanged("AccessFailedCount");
					this.OnAccessFailedCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
